-- USER table
CREATE TABLE IF NOT EXISTS "USER" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username TEXT NOT NULL UNIQUE,
  password TEXT
);

-- Seed USER1
INSERT INTO "USER" (id, username)
VALUES ('00000000-0000-0000-0000-000000000001', 'USER1')
ON CONFLICT (id) DO NOTHING;

-- VISITEVENT table
CREATE TABLE IF NOT EXISTS "VISITEVENT" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES "USER"(id),
  from_url TEXT NOT NULL,
  visited_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
